### ISSUE TITLE
a suggestion.....rem instead of em ?

### ISSUE THREAD

**Issue by nousename** [kristerkari/normalize.scss#11]
as the title says maybe an idea to use the defaults with rem instead of em

**Comment by kristerkari** [comment]
rem units do not work on all the browsers that normalize.css supports. That is why I don't think that it is a good idea. 

Source: http://caniuse.com/rem

**Comment by nousename** [comment]
ok was just curious - as my use of rem is generally such
that you have the backup of px and then follow it with the rem style
So anything, which is not a lot now, that does not suport rem, falls back to px definition

**Comment by kristerkari** [comment]
Alright. In this case using rem instead of em does not bring any extra value, which is also probably why normalize.css project does not use them.
