### ISSUE TITLE
sass compiling error

### ISSUE THREAD

**Issue by ukeboyska** [kristerkari/normalize.scss#14]
pulling down "normalize.scss": "3.0.0-alpha.1+normalize.2.1.3" and i'm getting this compiling errror:

"Syntax error: Invalid CSS after \" 'chrome'\": expected \")\", was \": null,\"\A on line 30 of /bower_components/normalize.scss/_normalize.scss from line 4 of main.scss"

any ideas?

**Comment by kristerkari** [comment]
I'm not a maintainer of the gem you are referring to. This is the correct one:
https://github.com/JohnAlbin/normalize-scss

**Comment by ukeboyska** [comment]
sorry! there's so many of these i got jumbled :-/ ...thanks!

**Comment by kristerkari** [comment]
No problem. I hope you get help from the other repo :)
