### ISSUE TITLE
Rename the `normalize.scss` file to `_normalize.scss`

### ISSUE THREAD

**Issue by LimeBlast** [kristerkari/normalize.scss#4]
I could be missing something here, but it seems to me that the `normalize.scss` file would be put to best use if it's @import'd into another (say `main.scss`) file. Because of this, if it was renamed, then it would follow SASS conventions (as seen here: http://sass-lang.com/tutorial.html#id1)?

I'm happy to submit this as a pull request if needed, but it is such a small change, I figured it was easier just let you know.

**Comment by kristerkari** [comment]
Thanks! Fixed.
