### ISSUE TITLE
No version number

### ISSUE THREAD

**Issue by kpeatt** [kristerkari/normalize.scss#5]
What version of Normalize is this using? Would be awesome to have it marked in the file so we know how up to date this is. Otherwise, awesome work!

**Comment by kristerkari** [comment]
Looking at the commits, I've updated changes from normalize.css about 7 months ago, so this project is outdated compared to normalize.css.

I'll try to do some updates and add version numbers at some point. :)

**Comment by kpeatt** [comment]
Updated to use latest version of normalize.css and include version number
